Assessment For Phase-3/Phase-three-final-project/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Phase_three_final_project.Helpers;
using Phase_three_final_project.Models;
using Stripe;

namespace Phase_three_final_project.Controllers
{
    public class CartController : Controller
    {
        ApplicationDBContext context;
        public string FirstName = "";

        public CartController()
        {
            context = new ApplicationDBContext();
        }
        public IActionResult Index()
        {
            if (SessionHelper.GetObjectFromJson<List<Items>>(HttpContext.Session, "cart") == null)
                return View("EmptyCart");
            else if(SessionHelper.GetObjectFromJson<User>(HttpContext.Session, "user") != null)
            {
                var cart = (SessionHelper.GetObjectFromJson<List<Items>>(HttpContext.Session, "cart"));
                ViewBag.cart = cart;
                ViewBag.total = cart.Sum(item => item.product.Price * item.Quantity);
                string t = (ViewBag.total).ToString();
                HttpContext.Session.SetString("total",t);
                ViewData["UserId"] = new SelectList(context.User, "UserId", "Username");
                return View();
            }
            else
                return RedirectToAction("Index", "Account");
        }

        public IActionResult Buy(int id)
        {
            if (SessionHelper.GetObjectFromJson<List<Items>>(HttpContext.Session, "cart") == null)
            {
                List<Items> cart = new List<Items>();
                cart.Add(new Items { product = context.Product.Find(id), Quantity = 1 });
                SessionHelper.setObjectasJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<Items> cart = SessionHelper.GetObjectFromJson<List<Items>>(HttpContext.Session, "cart");
                int index = IsExist(id);
                if (index != -1)
                    cart[index].Quantity++;
                else
                    cart.Add(new Items { product = context.Product.Find(id), Quantity = 1 });
                SessionHelper.setObjectasJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");
        }

        public int IsExist(int id)
        {
            List<Items> cart = SessionHelper.GetObjectFromJson<List<Items>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].product.ProductId == id)
                    return i;
            }
            return -1;
        }

        public IActionResult Checkout()
        {
           
            if (SessionHelper.GetObjectFromJson<User>(HttpContext.Session, "user") != null)
            {
                string amount= HttpContext.Session.GetString("total");
                ViewBag.Amount = Convert.ToDouble(amount);
                return View("Checkout");
            }

            else
                return RedirectToAction("Index", "Account");

        }

        public ActionResult Payment()
        {
            ViewBag.StripePublishKey = ConfigurationManager.AppSettings["pk_test_51JaFRgSC1tqaOG4n6Yqw1ecAJbe8C6E8xvxoVsW5JSu4jJqtPgU3uWO9mUMDllwVJw884wLHPhjc5mwwCdZL576l00KtVFiOGC"];
            return View();
        }

        [HttpPost]
        [Obsolete]
        public ActionResult Charge(string stripeToken, string stripeEmail)
        {
            StripeConfiguration.SetApiKey("pk_test_51JaFRgSC1tqaOG4n6Yqw1ecAJbe8C6E8xvxoVsW5JSu4jJqtPgU3uWO9mUMDllwVJw884wLHPhjc5mwwCdZL576l00KtVFiOGC");
            StripeConfiguration.ApiKey = "sk_test_51JaFRgSC1tqaOG4nqwb6D2jCpaZw3VxOtRLWzhXCIKtwTFEoKXs54bTYJFRsaOLfg3wyVFAsIOxT8H6BIyLUvpRR00OLQ2Daxg";
            string amount = HttpContext.Session.GetString("total");

            var myCharge = new ChargeCreateOptions();
            // always set these properties
            myCharge.Amount = (long?)Convert.ToDouble(amount); ;
            myCharge.Currency = "USD";
            myCharge.ReceiptEmail = stripeEmail;
            myCharge.Description = "Payment";
            myCharge.Source = stripeToken;
            myCharge.Capture = true;
            ViewBag.Token = myCharge.Source;
            return View(SessionHelper.GetObjectFromJson<Models.Address>(HttpContext.Session, "Address"));
        }

        [HttpPost]
        public IActionResult Create(Models.Address address)
        {
            
            context.Address.Add(address);
            context.SaveChanges();
            SessionHelper.setObjectasJson(HttpContext.Session, "Address", address);
            return RedirectToAction("Checkout");
        }

    }
}

Assessment For Phase-3/Phase-three-final-project/Controllers/DescriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Phase_three_final_project.Models;

namespace Phase_three_final_project.Controllers
{
    public class DescriptionController : Controller
    {
        private readonly ApplicationDBContext _context;

        public DescriptionController()
        {
            _context = new ApplicationDBContext();
        }

        // GET: Description
        public async Task<IActionResult> Index()
        {
            var applicationDBContext = _context.Description.Include(d => d.Product);
            return View(await applicationDBContext.ToListAsync());
        }

        // GET: Description/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var description = await _context.Description
                .Include(d => d.Product)
                .FirstOrDefaultAsync(m => m.DescriptionId == id);
            if (description == null)
            {
                return NotFound();
            }

            return View(description);
        }

        // GET: Description/Create
        public IActionResult Create()
        {
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "Name");
            return View();
        }

        // POST: Description/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DescriptionId,OS,Processor,Memory,HardDrive,ProductId")] Description description)
        {
            if (ModelState.IsValid)
            {
                _context.Add(description);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "Name", description.ProductId);
            return View(description);
        }

        // GET: Description/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var description = await _context.Description.FindAsync(id);
            if (description == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "Name", description.ProductId);
            return View(description);
        }

        // POST: Description/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DescriptionId,OS,Processor,Memory,HardDrive,ProductId")] Description description)
        {
            if (id != description.DescriptionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(description);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DescriptionExists(description.DescriptionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "Name", description.ProductId);
            return View(description);
        }

        // GET: Description/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var description = await _context.Description
                .Include(d => d.Product)
                .FirstOrDefaultAsync(m => m.DescriptionId == id);
            if (description == null)
            {
                return NotFound();
            }

            return View(description);
        }

        // POST: Description/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var description = await _context.Description.FindAsync(id);
            _context.Description.Remove(description);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DescriptionExists(int id)
        {
            return _context.Description.Any(e => e.DescriptionId == id);
        }
    }
}

Assessment For Phase-3/Phase-three-final-project/Controllers/ProductAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Phase_three_final_project.Models;

namespace Phase_three_final_project.Controllers
{
    public class ProductAdminController : Controller
    {
        private readonly ApplicationDBContext _context;

        public ProductAdminController()
        {
            _context = new ApplicationDBContext();
        }

        // GET: ProductAdmin
        public async Task<IActionResult> Index()
        {
            return View(await _context.Product.ToListAsync());
        }

        // GET: ProductAdmin/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: ProductAdmin/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProductAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,Name,Price,Image")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: ProductAdmin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: ProductAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,Name,Price,Image")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: ProductAdmin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: ProductAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.ProductId == id);
        }
    }
}

Assessment For Phase-3/Phase-three-final-project/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Phase_three_final_project.Models;

namespace Phase_three_final_project.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDBContext context;
        public ProductController()
        {
            context = new ApplicationDBContext();
        }
        public IActionResult Index()
        {
            var products = context.Product.ToList();
            return View(products);
        }

        public async Task<IActionResult> DetailsAsync(int? id)
        {
            var products = context.Product.Find(id);

            if (id == null)
            {
                return NotFound();
            }

            var product = await context.Product
                .Include(p => p.Description)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
    }
}

Assessment For Phase-3/Phase-three-final-project/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using Phase_three_final_project.Helpers;


    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Digital Retailers Inc</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/Default.css" />
    </head>
    <body>
        @if (SessionHelper.GetObjectFromJson<User>(Context.Session, "user") != null)
        {
            @if (SessionHelper.GetObjectFromJson<User>(Context.Session, "user").UserType.Equals("User"))
            {
                <header>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm  navbar-dark border-bottom box-shadow mb-3">
                        <div class="container">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><span class="text-3xl text-white font-semibold">Digital</span><span class="text-3xl text-danger font-semibold">Retailers Inc</span> </a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="text-end">
                                <span class="text-white" style="margin-right:12px;">Welcome @(SessionHelper.GetObjectFromJson<User>(Context.Session, "user").Username)!!!</span>
                                <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Logout</a>
                            </div>
                        </div>
                    </nav>
                </header>}
    else if (SessionHelper.GetObjectFromJson<User>(Context.Session, "user").UserType.Equals("Admin"))
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><span class="text-3xl text-white font-semibold">Digital</span><span class="text-3xl text-danger font-semibold">Retailers Inc</span> </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="ProductAdmin" asp-action="Index">ProductAdmin</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Description" asp-action="Index">Description</a>
                            </li>
                        </ul>
                    </div>
                    <div class="text-end">
                        <span class="text-white" style="margin-right:12px;">Admin @(SessionHelper.GetObjectFromJson<User>(Context.Session, "user").Username)</span>
                        <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Logout</a>
                    </div>
                </div>
            </nav>
        </header>
    }
        }
        else
        {
            <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
                    <div class="container">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><span class="text-3xl text-white font-semibold">Digital</span><span class="text-3xl text-danger font-semibold">Retailers Inc</span> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon text-white"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                                </li>
                            </ul>
                        </div>
                        <div class="text-end">
                            <a asp-controller="Account" asp-action="Index" class="btn btn-outline-success">Login</a>
                            <a asp-controller="Account" asp-action="RegisterForm" class="btn btn-outline-info">Register</a>
                        </div>
                    </div>
                </nav>
            </header>
        }
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container text-white">
                &copy; 2021 - Digital Retailers Inc - <a class="text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>